/** @file options.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef OPTIONS_H
#define OPTIONS_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef OPTIONS_PACKAGE
/** @brief the program name (used for printing errors) */
#define OPTIONS_PACKAGE "Docker Deploy"
#endif

#ifndef OPTIONS_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define OPTIONS_PACKAGE_NAME "Docker Deploy"
#endif

#ifndef OPTIONS_VERSION
/** @brief the program version */
#define OPTIONS_VERSION "0.0.1"
#endif

/** @brief Where the command line options are stored */
struct options
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * config_arg;	/**< @brief cfg file input.  */
  char * config_orig;	/**< @brief cfg file input original value given at command line.  */
  const char *config_help; /**< @brief cfg file input help description.  */
  int daemon_flag;	/**< @brief daemon (default=off).  */
  const char *daemon_help; /**< @brief daemon help description.  */
  int test_flag;	/**< @brief test (default=off).  */
  const char *test_help; /**< @brief test help description.  */
  int apply_flag;	/**< @brief apply (default=off).  */
  const char *apply_help; /**< @brief apply help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int config_given ;	/**< @brief Whether config was given.  */
  unsigned int daemon_given ;	/**< @brief Whether daemon was given.  */
  unsigned int test_given ;	/**< @brief Whether test was given.  */
  unsigned int apply_given ;	/**< @brief Whether apply was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct options_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure options (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure options (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *options_purpose;
/** @brief the usage string of the program */
extern const char *options_usage;
/** @brief the description string of the program */
extern const char *options_description;
/** @brief all the lines making the help output */
extern const char *options_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int options (int argc, char **argv,
  struct options *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use options_ext() instead
 */
int options2 (int argc, char **argv,
  struct options *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int options_ext (int argc, char **argv,
  struct options *args_info,
  struct options_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int options_dump(FILE *outfile,
  struct options *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int options_file_save(const char *filename,
  struct options *args_info);

/**
 * Print the help
 */
void options_print_help(void);
/**
 * Print the version
 */
void options_print_version(void);

/**
 * Initializes all the fields a options_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void options_params_init(struct options_params *params);

/**
 * Allocates dynamically a options_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized options_params structure
 */
struct options_params *options_params_create(void);

/**
 * Initializes the passed options structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void options_init (struct options *args_info);
/**
 * Deallocates the string fields of the options structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void options_free (struct options *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int options_required (struct options *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* OPTIONS_H */
